#' Calculate species condition
#'
#' This function calculates species condition from NEFSC survey data 'survdat::get_survdat_data(channel, getBio = TRUE, getLengths = TRUE)'
#' Methods derived from Laurel Smith (https://github.com/Laurels1/Condition/blob/master/R/RelConditionEPU.R)
#'
#' @param surveyData Data table. NEFSC survey data generated by \code{get_survdat_data.R}
#' @param areaPolygon sf object or character string. Default = "NEFSC strata". The default option uses the survey strata shapefile bundled with the package.
#' To use any other shapefile for stratification, the shapefile must be read in as an \link[sf]{sf} object and the \code{areaDescription} argument must be specified.
#' @param areaDescription Character String. Column name from \code{areaPolygon}
#'                       that contains the strata designations.
#' @param filterByArea Numeric vector. Set of areas to subset from the
#'  \code{areaDescription} of the \code{areaPolygon}.
#' @param filterBySeason Character string. Which seasons of the \code{surveyData}
#'  should be included.  Choices include "SPRING", "FALL", or "all".
#' @param channel

#### Notes:
# Should decide whether or not to use strata or EPU as the default areaPolygon (or option for both, see: 'calc_stratified_mean.R')
# filterBySeason default should be "FALL" since that is the only season that has been used in the past for condition calculations
# Do we want a species param? Or just have the function return for all species and then can be filtered when used for ESP/SOE/etc.?

# areaPolygon, areaDescription, filterByArea, and filterBySeason haven't been populated into the function yet

devtools::load_all()
source("../channel.R")
surveyData <- readRDS(
  "\\\\nefscdata\\EDAB_Datasets\\Workflows\\surveyBiologicalData.rds"
)
calc_condition(surveyData, channel)

calc_condition <- function(
  surveyData,
  channel,
  by_EPU = TRUE,
  by_sex = FALSE,
  length_break = NULL,
  more_than_20_years = TRUE,
  record_outliers = FALSE,
  output = "soe"
) {
  ### NOTE: Code chunks below, revised from NEesp2::species_condition - test before putting in function

  ### NOTE: FIGURE OUT HOW TO LOAD SHAPEFILE FROM SURVDAT, THEN FIX NEXT 7 LINES
  survey.data <- surveyData$survdat |>
    dplyr::left_join(NEesp2::strata_epu_key)
  # }

  # Change sex = NA to sex = 0
  fall <- survey.data |>
    dplyr::filter(.data$SEASON == "FALL") |>
    dplyr::mutate(
      sex = dplyr::if_else(is.na(.data$SEX), "0", as.character(.data$SEX))
    )

  # pull LW data from 'get_length_weight' and filter to fall
  lwpull <- get_length_weight(channel)
  lwfall <- lwpull$data |>
    dplyr::select(
      .data$SVSPP,
      .data$CATCHSEX,
      .data$SVLWCOEFF_FALL,
      .data$SVLWEXP_FALL
    )

  # pull species common names and SVSPP from 'get_species'
  species <- get_species(channel)
  species_data <- species$data |>
    dplyr::select(.data$SVSPP, .data$COMNAME) |>
    tidyr::drop_na(.data$SVSPP, .data$COMNAME)

  #group LWfall and species_data by SVSPP
  combined_lw_species <- lwfall |>
    dplyr::inner_join(species_data, by = "SVSPP")

  # get sex info from 'get_sex' and join with combined_lw_species
  sex_data <- get_sex(channel)
  sex <- sex_data$data |>
    dplyr::rename(CATCHSEX = SEX)

  # add male, female, and unsexed descriptions to CATCHSEX numbers
  ### NOTE: CATCHSEX 3-7 apply to Northern Shrimp and Lobster Only
  LWsexed <- combined_lw_species |>
    dplyr::inner_join(sex, by = "CATCHSEX") |>
    dplyr::mutate(
      SEX_DESCRIPTION = dplyr::case_when(
        CATCHSEX == 0 ~ "Unsexed",
        CATCHSEX == 1 ~ "Male",
        CATCHSEX == 2 ~ "Female",
        TRUE ~ SEX_DESCRIPTION # Keeps original value if CATCHSEX is anything else (e.g., NA)
      )
    )

  # combine LW/sex/species data with Fall survey data
  new_data <- LWsexed |>
    dplyr::inner_join(fall, by = c("SVSPP", "CATCHSEX"))

  # filters out values without losing rows with NAs:
  mergewt <- dplyr::filter(new_data, is.na(.data$INDWT) | .data$INDWT < 900)
  mergewtno0 <- dplyr::filter(mergewt, is.na(.data$INDWT) | .data$INDWT > 0.004)
  mergelenno0 <- dplyr::filter(
    mergewtno0,
    is.na(.data$LENGTH) | .data$LENGTH > 0
  )
  mergelen <- dplyr::filter(mergelenno0, !is.na(.data$LENGTH))
  mergeindwt <- dplyr::filter(mergelen, !is.na(.data$INDWT))
  mergeLW <- dplyr::filter(mergeindwt, !is.na(.data$SVLWCOEFF_FALL))

  ### Calculate species condition ###

  condcalc <- dplyr::mutate(
    mergeLW,
    predwt = (exp(.data$SVLWCOEFF_FALL)) * .data$LENGTH^.data$SVLWEXP_FALL,
    RelCond = .data$INDWT / .data$predwt
  ) |>
    dplyr::filter(is.na(.data$RelCond) | .data$RelCond < 300) %>%
    dplyr::group_by(.data$SVSPP, .data$SEX) %>%
    dplyr::mutate(
      mean = mean(.data$RelCond),
      sd = stats::sd(.data$RelCond)
    ) |>
    dplyr::ungroup() |>
    # might want to update this outlier removal eventually
    dplyr::mutate(
      outlier = .data$RelCond > (.data$mean + (2 * .data$sd)) |
        .data$RelCond < (.data$mean - (2 * .data$sd))
    )

  message(paste0(
    "Removing ",
    sum(condcalc$outlier, na.rm = TRUE),
    " outliers from the data set."
  ))

  if (record_outliers) {
    outliers <- condcalc |>
      dplyr::filter(.data$outlier == TRUE)
  }

  condcalc <- condcalc |>
    dplyr::filter(.data$outlier == FALSE) |>
    dplyr::filter(is.na(.data$sex) | .data$sex != 4) %>%
    dplyr::mutate(sexMF = .data$sex)

  species.codes <- survdat::get_species(channel = channel)$data |>
    dplyr::rename(Species = COMNAME) |>
    dplyr::select(Species, SVSPP) |>
    tidyr::drop_na()

  cond.epu <- dplyr::left_join(condcalc, species.codes, by = c("SVSPP"))

  # Summarize annually -- parameterized groupings
  grouping_vars <- c("Species", "YEAR", "EPU")

  if (by_sex) {
    grouping_vars <- c(grouping_vars, "sexMF")
  }

  if (!is.null(length_break)) {
    cond.epu <- cond.epu |>
      dplyr::mutate(
        length_group = cut(
          .data$LENGTH,
          breaks = length_break,
          include.lowest = TRUE
        )
      )
    grouping_vars <- c(grouping_vars, "length_group")
  }

  grouped_condition <- cond.epu |>
    dplyr::group_by(!!!rlang::syms(grouping_vars))

  condition <- grouped_condition %>%
    dplyr::summarize(
      MeanCond = mean(.data$RelCond),
      nCond = dplyr::n()
    ) |>
    dplyr::ungroup() |>
    dplyr::filter(.data$nCond >= 3) |>
    # select columns
    dplyr::select(dplyr::all_of(c(grouping_vars, "MeanCond", "nCond"))) |>
    # group again, without YEAR
    dplyr::group_by(
      !!!rlang::syms(grouping_vars[-which(grouping_vars == "YEAR")])
    ) |>
    # filter to only species with 20+ years of data
    dplyr::mutate(n = dplyr::n())

  return(condition)
}
