# =========================================================================
# Title: Issue 79 - Review calc_swept_area()
# Purpose: Test the current state of survdat::calc_swept_area() using 
#          vignette sample data before implementing fixes for missing units, 
#          required field checks, and filterBySeason defaults if needed.
# =========================================================================

# 0. Setup ----------------------------------------------------------------
library(survdat)
library(tidyverse)

message("Setting up test environment for Issue #79 using package sample data...")

# Load the package sample data generated by Andy's script
data("sampleRaw", package = "survdat")

# Alternatively, if you want to test with conversion factors:
# data("sampleRawWithConversion", package = "survdat")

test_data <- sampleRaw

# Inspect the available columns to know what we are working with
message("Columns available in test_data: ", paste(names(test_data), collapse = ", "))


# 1. Test Output Units ----------------------------------------------------
message("\n--- Test 1: Checking output for units ---")

# Run the function as-is to see the baseline output
baseline_results <- calc_swept_area(test_data)

message("Output columns from calc_swept_area():")
print(names(baseline_results))


# 2. Test filterBySeason Behavior -----------------------------------------
message("\n--- Test 2: Checking filterBySeason parameter ---")

# What happens if we don't specify a season? (Does it default to SPRING/FALL or keep all?)
message("Seasons in baseline output: ", paste(unique(baseline_results$SEASON), collapse = ", "))

# What happens if we pass a specific season?
tryCatch({
  spring_results <- calc_swept_area(test_data, filterBySeason = "SPRING")
  message("Seasons in spring-filtered output: ", paste(unique(spring_results$SEASON), collapse = ", "))
}, error = function(e) {
  message("Filtering by 'SPRING' threw an error: ", e$message)
})


# 3. Test Missing Fields Handling -----------------------------------------
message("\n--- Test 3: Checking missing field errors ---")

# Break the dataset by removing fields that swept area math needs

bad_data <- test_data |> 
  select(-STRATUM, -BIOMASS) 

tryCatch({
  bad_results <- calc_swept_area(bad_data)
  message("WARNING: The function ran successfully despite missing STRATUM and BIOMASS.")
}, error = function(e) {
  message("The function failed (as expected). Here is the error it threw:")
  message("--> ", e$message)
})