#' Calculate species condition
#'
#' Calculates species [condition](https://noaa-edab.github.io/tech-doc/condition.html?q=condit#condition) from NEFSC survey data
#'
#' @section Species Coverage:
#' The choice of \code{lengthweight} parameter determines species availability. When using
#' \code{lengthweight = "Wigley"}, species coverage is constrained to the static parameters
#' from [Wigley et al. (2003)](#references) and does not include Blueback herring or
#' Northern Searobin. Using \code{lengthweight = "survdat"} includes all species from [Wigley et al. (2003)](#references) plus Blueback herring and Northern Searobin.
#'
#' @section References:
#' Methods are outlined in the [technical documentation](https://noaa-edab.github.io/tech-doc/condition.html?q=condit#condition) for the State of the Ecosystem report
#'
#' Wigley SE, McBride HM, McHugh NJ. Length-weight relationships for 74 fish species collected during NEFSC research vessel bottom trawl surveys, 1992-99. 2003; Available: \url{https://repository.library.noaa.gov/view/noaa/3346}
#'
#'
#' @inheritParams get_survdat_data
#' @param surveyData Data table. NEFSC survey data generated by [survdat::get_survdat_data(channel, getBio = TRUE)]
#' @param lengthweight character string. Length-weight coefficients. Default value is 'Wigley'. Options = "survdat" or "Wigley". 'lengthweight = "survdat"' uses length-weight parameters from the NEFSC survdat database generated by [survdat::get_length_weight()]. 'lengthweight = "Wigley"' uses a static set of length-weight parameters from Wigley et al. (2003).
#' @param aggregate_by vector. Default value is 'EPU'. Spatial scale to aggregate by: "EPU", "strata", or "none".
#' @param by_sex logical. Default value is FALSE. If TRUE, calculates condition by sex. If FALSE, calculates condition across sexes.
#' @param length_break numeric vector. Length intervals (cm) in which to calculation condition. Default (NULL) combines all lengths. Otherwise condition in calculated within provided interval. User must specify minimum and maximum lengths. For example to calculate condition for two groups \code{[0-20]} and \code{(21-70]}, use `length_breaks = c(0,20,70)`
#'
#' @examples
#'
#' \dontrun{
#' # Pull data and apply conversion corrections
#' data <- get_survdat_data(channel, getBio = TRUE)
#' # Calculate condition aggregated by EPU, with Wigley length-weight coefficients, and with length breaks of 0, 20, and 50
#' calc_condition(channel = channel, surveyData=data$survdat, lengthweight = "Wigley", aggregate_by = "EPU", by_sex = FALSE, length_break = c(0, 20, 50))
#'
#' # Calculate condition aggregated by strata, with survdat length-weight coefficients, and without length breaks
#' calc_condition(channel = channel, surveyData=data$survdat, lengthweight = "survdat", aggregate_by = "strata", by_sex = FALSE, length_break = NULL)
#'}
#'
#' @export

calc_condition <- function(
  channel,
  surveyData,
  lengthweight = 'Wigley',
  aggregate_by = 'EPU',
  by_sex = FALSE,
  length_break = NULL
) {
  # add 0 to length_break if needed
  if (!0 %in% length_break & !is.null(length_break)) {
    length_break <- c(0, length_break)
  }

  survey.data <- surveyData |>
    dplyr::left_join(survdat::EPUstrata, by = c("STRATUM"))

  # Change sex = NA to sex = 0
  fall <- survey.data |>
    dplyr::filter(SEASON == "FALL") |>
    dplyr::mutate(
      sex = dplyr::if_else(is.na(SEX), "0", as.character(SEX))
    )

  if (lengthweight == "survdat") {
    # pull LW data from 'get_length_weight' and filter to fall
    survdat_lw <- survdat::get_length_weight(channel)
    lwfall <- survdat_lw$data |>
      dplyr::select(
        SVSPP,
        CATCHSEX,
        SVLWCOEFF_FALL,
        SVLWEXP_FALL
      )
  }

  if (lengthweight == "Wigley") {
    lwfall <- survdat::Wigley_LW |>
      dplyr::filter(SEASON == "FALL") |>
      dplyr::rename(
        SVSPP = LW_SVSPP,
        SVLWCOEFF_FALL = lna,
        SVLWEXP_FALL = b
      ) |>
      dplyr::select(
        SVSPP,
        SVLWCOEFF_FALL,
        SVLWEXP_FALL,
        Gender
      ) |>
      dplyr::mutate(
        CATCHSEX = dplyr::case_when(
          Gender == "Combined" | Gender == "Unsexed" ~ as.character(0),
          Gender == "Male" ~ as.character(1),
          Gender == "Female" ~ as.character(2),
          TRUE ~ NA
        )
      )
    lwfall$CATCHSEX <- as.integer(lwfall$CATCHSEX)
  }

  # pull species common names and SVSPP from 'get_species'
  species <- survdat::get_species(channel)
  species_data <- species$data |>
    dplyr::select(SVSPP, COMNAME) |>
    tidyr::drop_na(SVSPP, COMNAME)

  #group LWfall and species_data by SVSPP
  combined_lw_species <- lwfall |>
    dplyr::inner_join(species_data, by = "SVSPP")

  # get sex info from 'get_sex' and join with combined_lw_species
  sex_data <- survdat::get_sex(channel)
  sex <- sex_data$data |>
    dplyr::rename(CATCHSEX = SEX)

  # add male, female, and unsexed descriptions to CATCHSEX numbers
  ### NOTE: CATCHSEX 3-7 apply to Northern Shrimp and Lobster Only
  LWsexed <- combined_lw_species |>
    dplyr::inner_join(sex, by = "CATCHSEX") |>
    dplyr::mutate(
      SEX_DESCRIPTION = dplyr::case_when(
        CATCHSEX == 0 ~ "Unsexed",
        CATCHSEX == 1 ~ "Male",
        CATCHSEX == 2 ~ "Female",
        TRUE ~ SEX_DESCRIPTION # Keeps original value if CATCHSEX is anything else (e.g., NA)
      )
    )

  # combine LW/sex/species data with Fall survey data
  new_data <- LWsexed |>
    dplyr::inner_join(fall, by = c("SVSPP", "CATCHSEX"))

  # filters out values without losing rows with NAs:
  mergewt <- dplyr::filter(new_data, is.na(INDWT) | INDWT < 900)
  mergewtno0 <- dplyr::filter(mergewt, is.na(INDWT) | INDWT > 0.004)
  mergelenno0 <- dplyr::filter(
    mergewtno0,
    is.na(LENGTH) | LENGTH > 0
  )
  mergelen <- dplyr::filter(mergelenno0, !is.na(LENGTH))
  mergeindwt <- dplyr::filter(mergelen, !is.na(INDWT))
  mergeLW <- dplyr::filter(mergeindwt, !is.na(SVLWCOEFF_FALL))

  ### Calculate species condition ###

  condcalc <- dplyr::mutate(
    mergeLW,
    predwt = (exp(SVLWCOEFF_FALL)) * LENGTH^SVLWEXP_FALL,
    RelCond = INDWT / predwt
  ) |>
    dplyr::filter(is.na(RelCond) | RelCond < 300) |>
    dplyr::group_by(SVSPP, SEX) |>
    dplyr::mutate(
      mean = mean(RelCond),
      sd = stats::sd(RelCond)
    ) |>
    dplyr::ungroup()

  condcalc <- condcalc |>
    dplyr::filter(is.na(sex) | sex != 4) |>
    dplyr::mutate(sexMF = sex)

  species.codes <- survdat::get_species(channel = channel)$data |>
    dplyr::rename(Species = COMNAME) |>
    dplyr::select(Species, SVSPP) |>
    tidyr::drop_na()

  cond.epu <- dplyr::left_join(condcalc, species.codes, by = c("SVSPP"))

  # Summarize annually -- parameterized groupings
  grouping_vars <- c("Species", "YEAR")

  if (aggregate_by == "strata") {
    grouping_vars <- c(grouping_vars, "STRATUM")
  }

  if (aggregate_by == "EPU") {
    grouping_vars <- c(grouping_vars, "EPU")
  }

  if (by_sex) {
    grouping_vars <- c(grouping_vars, "sexMF")
  }

  if (!is.null(length_break)) {
    cond.epu <- cond.epu |>
      dplyr::mutate(
        length_group = cut(
          LENGTH,
          breaks = length_break,
          include.lowest = TRUE
        )
      )
    grouping_vars <- c(grouping_vars, "length_group")
  }

  grouped_condition <- cond.epu |>
    dplyr::group_by(!!!rlang::syms(grouping_vars))

  if (aggregate_by == "none") {
    grouped_condition <- grouped_condition
  }

  condition <- grouped_condition |>
    dplyr::summarize(
      MeanCond = mean(RelCond),
      nCond = dplyr::n()
    ) |>
    dplyr::ungroup() |>
    dplyr::filter(nCond >= 3) |>
    # select columns
    dplyr::select(dplyr::all_of(c(grouping_vars, "MeanCond", "nCond"))) |>
    # group again, without YEAR
    dplyr::group_by(
      !!!rlang::syms(grouping_vars[-which(grouping_vars == "YEAR")])
    ) |>
    # filter to only species with 20+ years of data
    dplyr::mutate(nYears = dplyr::n()) |>
    dplyr::filter(nYears >= 20)

  return(condition)
}
