#'Post stratify NEFSC survey data
#'
#'Uses a shapefile to post stratify survey data collected
#'during the NEFSC surveys
#'
#'@family Survdat
#'
#'@param survdat NEFSC survey data generated by Survdat.R.
#'@param stratum R object containing the shapefile.
#'@param strata.col Column name from stratum that contains the strata designations.
#'@param na.keep Logical value to indicate whether original strata names should be retained.
#'
#'@return Returns a survdat object with new strata designations labeled as \code{newstrata}.
#'
#'
#'@export


poststrat <- function (survdat, stratum, strata.col = 'EPU', na.keep = F) {
  # if (!requireNamespace("rgdal", quietly = TRUE)) {
  #   stop("rgdal needed for this function to work. Please install it.",
  #        call. = FALSE)
  # }

  #Data
  x <- data.table::copy(survdat)

  #Use only station data
  data.table::setkey(x, CRUISE6, STRATUM, STATION)
  stations <- unique(x, by = data.table::key(x))
  stations <- stations[, list(CRUISE6, STRATUM, STATION, LAT, LON)]

  #Convert to spatial points data frame
  sp::coordinates(stations) <- ~LON+LAT
  stations@proj4string  <- sp::CRS('+init=epsg:4326') #Lat/Lon code
  lcc <- sp::CRS("+proj=lcc +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-72 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 ") #Lambert Conformal Conic
  stations <- sp::spTransform(stations, lcc)

  #Identify tows within new strata
  stratum     <- sp::spTransform(stratum, lcc)
  names(stratum@data)[which(names(stratum@data) == strata.col)] <- "strata.col"
  stations$newstrata <- sp::over(stations, stratum)[ ,'strata.col']
  names(stratum@data)[which(names(stratum@data) == "strata.col")] <- strata.col

  #Output data (convert spatial data frame back to lat/lon)
  stations <- sp::spTransform(stations, sp::CRS('+init=epsg:4326'))
  sta.data <- data.table::as.data.table(as.data.frame(stations))
  if(na.keep == F) sta.data <- sta.data[!is.na(newstrata), ]
  sta.data[, c('LAT', 'LON') := NULL]
  out <- base::merge(x, sta.data, by = c('CRUISE6', 'STRATUM', 'STATION'))

  return(out)
}

