#'Calculate stratified mean biomass and abundance
#'
#'Calculates the stratified mean biomass and abundance.  Also calculates the associated
#'variance and standard error.  Requires you to run stratprep() to survdat object beforehand.
#'
#'@family Survdat
#'
#'@param survdat NEFSC survey data generated by Survdat.R and modified by stratprep().
#'@param groups Specify a particular group you want.  The default "all" will calculate
#'means for all groups in the group.col.
#'@param mergesexFlag Logical value to merge sexed species such as dogfish.
#'@param sex.col Column of survdat containing the sex of the group.  If mergesexFlag is true,
#'this parameter is ignored.
#'@param group.col Column of survdat upon which the means are based (i.e. SVSPP).
#'@param strata.col Column of survdat containing strata designations.
#'@param poststrat Logical value indicating whether the original strata design was
#'used or not.  Changes the calculation for variance.
#'@param nsta.col Column of survdat containing the number of stations per strata.
#'@param area.wgt Column of survdat containing the strata weights.
#'@param weight Column of survdat containing the biomass per station.
#'@param number Column of survdat containing the abundance per station.
#'
#'@return Returns a table with stratified mean biomass and abundance for each group
#'indicated by the group.col parameter.  In addition, the variance and standard error
#'for both means are provided.
#'
#'@importFrom data.table "key"
#'
#'@export


strat_mean <- function (prepData, groupDescription = "SVSPP", filterByGroup = "all", 
                        mergesexFlag = T, areaDescription, poststratFlag) {

  stratmeanData <- data.table::copy(prepData)
  
  #areaDescription may be NULL if passed from calc_stratified_mean so need to assign
  #default within this function
  if(is.null(areaDescription)) areaDescription <- 'STRATA'
  
  #Remove length data if present
  data.table::setkey(stratmeanData, CRUISE6, STRATUM, STATION, SVSPP, CATCHSEX)
  stratmeanData <- unique(stratmeanData, by = key(stratmeanData))
  stratmeanData[, c('LENGTH', 'NUMLEN') := NULL]

  data.table::setnames(stratmeanData, c(groupDescription, areaDescription),
                       c('group', 'strat'))

  #Merge sex or keep separate
  if(mergesexFlag == F) stratmeanData[, group := paste(group, CATCHSEX, sep = '')]

  data.table::setkey(stratmeanData, CRUISE6, strat, STATION, group)
  stratmeanData[, BIOMASS   := sum(BIOMASS),   by = key(stratmeanData)]
  stratmeanData[, ABUNDANCE := sum(ABUNDANCE), by = key(stratmeanData)]
  stratmeanData <- unique(stratmeanData, by = key(stratmeanData))

  #Fix Na's
  stratmeanData[is.na(BIOMASS),   BIOMASS   := 0]
  stratmeanData[is.na(ABUNDANCE), ABUNDANCE := 0]

  #Calculate total number of stations per year
  data.table::setkey(stratmeanData, strat, YEAR)
  N <- unique(stratmeanData, by = key(stratmeanData))
  N <- N[, sum(ntows), by = 'YEAR']
  data.table::setnames(N, 'V1', 'N')

  #Subset data if necessary
  if(filterByGroup[1] != 'all'){
    if(mergesexFlag == F) filterByGroup <- c(paste0(filterByGroup, 0), 
                                             paste0(filterByGroup, 1),
                                             paste0(filterByGroup, 2), 
                                             paste0(filterByGroup, 3))
    stratmeanData <- stratmeanData[group %in% filterByGroup, ]
  }

  #Calculate weight per tow and number per tow
  data.table::setkey(stratmeanData, group, strat, YEAR)

  stratmeanData[, biomass.tow   := sum(BIOMASS)   / ntows, by = key(stratmeanData)]
  stratmeanData[, abundance.tow := sum(ABUNDANCE) / ntows, by = key(stratmeanData)]

  #Calculated stratified means
  stratmeanData[, weighted.biomass   := biomass.tow   * W.h]
  stratmeanData[, weighted.abundance := abundance.tow * W.h]

  #Variance - need to account for zero catch
  stratmeanData[, n.zero := ntows - length(BIOMASS), by = key(stratmeanData)]

  stratmeanData[, zero.var.b := n.zero * (0 - biomass.tow)^2]
  stratmeanData[, vari.b := (BIOMASS - biomass.tow)^2]
  stratmeanData[, Sh.2.b := (zero.var.b + sum(vari.b)) / (ntows - 1), by = key(stratmeanData)]
  stratmeanData[is.nan(Sh.2.b), Sh.2.b := 0]

  stratmeanData[, zero.var.a := n.zero * (0 - abundance.tow)^2]
  stratmeanData[, vari.a := (ABUNDANCE - abundance.tow)^2]
  stratmeanData[, Sh.2.a := (zero.var.a + sum(vari.a)) / (ntows - 1), by = key(stratmeanData)]
  stratmeanData[is.nan(Sh.2.a), Sh.2.a := 0]

  stratmeanData <- unique(stratmeanData, by = key(stratmeanData))

  stratmeanData <- merge(stratmeanData, N, by = 'YEAR')

  #Stratified mean
  setkey(stratmeanData, group, YEAR)

  stratmeanData[, strat.biomass := sum(weighted.biomass),   by = key(stratmeanData)]
  stratmeanData[, strat.abund   := sum(weighted.abundance), by = key(stratmeanData)]

  #Stratified variance
  if(poststratFlag == F){
    stratmeanData[, biomass.var := sum(((W.h^2) * Sh.2.b) / ntows), by = key(stratmeanData)]
    stratmeanData[, abund.var   := sum(((W.h^2) * Sh.2.a) / ntows), by = key(stratmeanData)]
  }

  if(poststratFlag == T){
    stratmeanData[, biomass.var := sum(Sh.2.b * W.h) / N + sum((1 - W.h) * Sh.2.b) / N^2, by = key(stratmeanData)]
    stratmeanData[, abund.var   := sum(Sh.2.a * W.h) / N + sum((1 - W.h) * Sh.2.a) / N^2, by = key(stratmeanData)]

  }

  #standard error of the means
  stratmeanData[, biomass.SE := sqrt(biomass.var), by = key(stratmeanData)]
  stratmeanData[, abund.SE   := sqrt(abund.var),   by = key(stratmeanData)]

  #Delete extra rows/columns
  stratmeanData <- unique(stratmeanData, by = key(stratmeanData))
  stratmeanData <- stratmeanData.means[, list(YEAR, group, CATCHSEX, N, 
                                              strat.biomass, biomass.var, biomass.SE, 
                                              strat.abund, abund.var, abund.SE)]
  if(mergesexFlag == T) stratmeanData[, CATCHSEX := NULL]

  if(mergesexFlag == F){
    stratmeanData[, glen := nchar(group)]
    for(i in 2:4){
      stratmeanData[glen == i, group := as.numeric(substr(group, 1, i - 1))]
    }
    stratmeanData[, glen := NULL]
    data.table::setkey(stratmeanData, YEAR, SVSPP, CATCHSEX)
  }

  data.table::setnames(stratmeanData, 'group', groupDescription)

  return(stratmeanData)
}
