#'Prepare survey data for calculating stratified mean
#'
#'Calculates the number of tows per strata and strata weight.  Run before
#'subsetting the data by species of interest to ensure all stations are accounted.
#'
#'@family Survdat
#'
#'@param survdat Data table. NEFSC survey data generated by \code{get_survdat_data.R}
#'@param areas Data table. nx2 table containing stratum names and areas. (see \code{get_area}).
#'@param strata.col Character string. Column name from stratum that contains the strata designations.
#'
#'@return Returns a survdat object with added columns for the number of tows (ntows) and
#'stratum weights (W.h).
#'
#'@importFrom data.table "key"
#'
#'@export


strat_prep <- function (survdata, areas, strat.col) {
  x <- data.table::copy(survdata)
  y <- data.table::copy(areas)

  data.table::setnames(x, strat.col, 'STRAT')
  data.table::setnames(y, c("STRATUM", "Area"), c('STRAT',   'S.AREA'))

  # if using not using survey strata shapefile
  if(strat.col != 'STRATA'){
    x[, STATION2 := as.numeric(paste0(STRATUM, STATION))][]
    data.table::setnames(x, c('STATION', 'STATION2'), c('ORIGSTATION', 'STATION'))
  }

  #Station data - Finds list of distinct stations sampled through time
  data.table::setkey(x, CRUISE6, STRAT, STATION)
  stations <- unique(x, by = key(x))
  stations <- stations[, list(YEAR, CRUISE6, STRAT, STATION)]

  #x %>% dplyr::distinct(YEAR,CRUISE6,STRAT,STATION)
  # Count the number of stations in each year for each Region
  data.table::setkey(stations, YEAR, STRAT)
  stations[, ntows := length(STATION), by = key(stations)]

  #Merge stations and area
  stations <- base::merge(stations, y, by = 'STRAT', all.x = T)

  #Calculate stratum weight
  data.table::setkey(stations, 'YEAR', 'STRAT')
  strat.year <- unique(stations, by = key(stations))
  strat.year[, c('CRUISE6', 'STATION', 'ntows') := NULL]
  strat.year[, W.h := S.AREA / sum(S.AREA, na.rm = T), by = YEAR]
  strat.year[, W.h := as.vector(W.h)] #Drops the units from the area
  strat.year[is.na(W.h), W.h := 0]
  strat.year[, S.AREA := NULL]

  #Merge back
  stations <- merge(stations, strat.year, by = key(stations))

  #Merge catch with station data
  strat.survdat <- merge(x, stations, by = c('YEAR', 'CRUISE6', 'STRAT', 'STATION'))

  data.table::setnames(strat.survdat, c('STRAT', 'S.AREA'),
           c(strat.col, "Area"))

  if(strat.col != 'STRATA'){
    data.table::setnames(strat.survdat, c('STATION', 'ORIGSTATION'), c('STATION2', 'STATION'))
    strat.survdat[, STATION2 := NULL]
  }

  return(strat.survdat)
}
