#'Prepare survey data for calculating stratified mean
#'
#'Calculates the number of tows per strata and strata weight.  Run before
#'subsetting the data by species of interest to ensure all stations are accounted.
#'
#'@family Survdat
#'
#'@param survdat NEFSC survey data generated by Survdat.R.
#'@param areas R object with stratum areas.  Can be generated by getarea().
#'@param strata.col Column name containing strata designations.  Must be the same for
#'survdat and areas.
#'@param area.col Column name containing the stratum areas in the areas object.
#'
#'@return Returns a survdat object with added columns for the number of tows (ntows) and
#'stratum weights (W.h).
#'@import data.table
#'@export
stratprep <- function (survdat, areas, strat.col, area.col = 'Area') {
  x <- copy(survdat)
  y <- copy(areas)

  setnames(x, strat.col, 'STRAT')
  setnames(y, c(strat.col, area.col),
           c('STRAT',   'S.AREA'))
  if(strat.col != 'STRATUM'){
    x[, STATION2 := as.numeric(paste0(STRATUM, STATION))][]
    setnames(x, c('STATION', 'STATION2'), c('ORIGSTATION', 'STATION'))
  }

  #Station data - remove catch/length
  setkey(x, CRUISE6, STRAT, STATION)
  stations <- unique(x, by = key(x))
  stations <- stations[, list(YEAR, CRUISE6, STRAT, STATION)]

  #count stations
  setkey(stations, YEAR, STRAT)
  stations[, ntows := length(STATION), by = key(stations)]

  #Merge stations and area
  stations <- merge(stations, y, by = 'STRAT', all.x = T)

  #Calculate stratum weight
  setkey(stations, 'YEAR', 'STRAT')
  strat.year <- unique(stations, by = key(stations))
  strat.year[, c('CRUISE6', 'STATION', 'ntows') := NULL]
  strat.year[, W.h := S.AREA / sum(S.AREA, na.rm = T), by = YEAR]
  strat.year[is.na(W.h), W.h := 0]
  strat.year[, S.AREA := NULL]

  #Merge back
  stations <- merge(stations, strat.year, by = key(stations))

  #Merge catch with station data
  strat.survdat <- merge(x, stations, by = c('YEAR', 'CRUISE6', 'STRAT', 'STATION'))

  setnames(strat.survdat, c('STRAT', 'S.AREA'),
           c(strat.col, area.col))

  if(strat.col != 'STRATUM'){
    setnames(strat.survdat, c('STATION', 'ORIGSTATION'), c('STATION2', 'STATION'))
    strat.survdat[, STATION2 := NULL]
  }

  return(strat.survdat)
}
